services:
  # Frontend React - Vetrina Landing Page
  vetrina-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ravai_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - frontend_build:/app/dist
    networks:
      - web-proxy

volumes:
  frontend_build:
    driver: local

networks:
  web-proxy:
    external: true